name: "Setup and install"
description: "Common setup steps for Actions"

inputs:
  skip-turbo:
    description: "Skip installing turbo globally"
    required: false
    default: "false"
  skip-node:
    description: "Skip installing node"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2.1.2
    
    - if: ${{ inputs.skip-node != 'true' }}
      uses: actions/setup-node@v4

    - name: Install Dependencies
      shell: bash
      run: bun ci
