packages:
  - apps/*/*
  - packages/*/*
  - tooling/*

catalog:
  '@bacons/text-decoder': ^0.0.0
  '@biomejs/biome': ^2.2.5
  '@casl/ability': ^6.7.3
  '@clack/prompts': ^0.7.0
  '@formkit/auto-animate': ^0.8.2
  '@hookform/resolvers': ^5.1.1
  '@motify/components': ^0.18.0
  '@neondatabase/serverless': ^1.0.1
  '@node-rs/argon2': ^1.8.3
  '@oslojs/crypto': ^1.0.1
  '@oslojs/encoding': ^1.1.0
  'cep-promise': ^4.4.1
  '@radix-ui/react-alert-dialog': ^1.1.13
  '@radix-ui/react-avatar': ^1.1.9
  '@radix-ui/react-checkbox': ^1.3.1
  '@radix-ui/react-context-menu': ^2.2.14
  '@radix-ui/react-dialog': ^1.1.13
  'libphonenumber-js': ^1.12.24
  'react-phone-number-input': ^3.4.12
  '@radix-ui/react-dropdown-menu': ^2.1.14
  '@radix-ui/react-label': ^2.1.6
  '@radix-ui/react-navigation-menu': ^1.2.12
  '@radix-ui/react-popover': ^1.1.13
  '@radix-ui/react-radio-group': ^1.3.6
  '@radix-ui/react-scroll-area': ^1.2.8
  '@radix-ui/react-select': ^2.2.4
  '@radix-ui/react-separator': ^1.1.6
  '@radix-ui/react-slot': ^1.2.2
  '@radix-ui/react-switch': ^1.2.4
  '@radix-ui/react-tabs': ^1.1.11
  '@radix-ui/react-toast': ^1.2.13
  '@radix-ui/react-toggle': ^1.1.8
  '@radix-ui/react-tooltip': ^1.2.6
  '@radix-ui/react-visually-hidden': ^1.2.2
  '@react-email/components': ^0.0.33
  '@react-email/render': 0.0.13
  '@react-native-async-storage/async-storage': 1.23.1
  '@react-native-community/datetimepicker': ^8.2.0
  '@react-native-google-signin/google-signin': ^12.2.1
  '@shopify/flash-list': 1.6.4
  '@t3-oss/env-core': ^0.9.2
  '@t3-oss/env-nextjs': ^0.13.6
  '@tamagui/babel-plugin': ^1.110.5
  '@tamagui/cli': ^1.110.5
  '@tamagui/config': ^1.110.5
  '@tamagui/font-inter': ^1.110.5
  '@tamagui/lucide-icons': ^1.110.5
  '@tamagui/toast': ^1.110.5
  '@tanstack/react-table': ^8.21.2
  '@types/babel__core': ^7.20.5
  '@types/deep-diff': ^1.0.5
  '@types/ms': ^0.7.34
  '@types/node': 22.15.0
  '@types/object.groupby': ^1.0.4
  '@upstash/qstash': ^2.7.12
  '@upstash/redis': ^1.31.6
  '@vercel/analytics': ^1.2.2
  '@vercel/speed-insights': ^1.0.10
  arctic: ^1.9.1
  burnt: ^0.12.2
  chalk: ^5.3.0
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  cmdk: ^1.0.4
  cobe: ^0.6.3
  date-fns: ^3.6.0
  dayjs: ^1.11.11
  deep-diff: ^1.0.2
  discord-api-types: ^0.37.91
  dotenv-cli: ^7.4.4
  drizzle-kit: ^0.31.0
  drizzle-orm: ^0.44.2
  drizzle-seed: ^0.3.1
  drizzle-zod: ^0.8.2
  embla-carousel-react: 8.0.0-rc22
  es-toolkit: 1.39.10
  framer-motion: ^11.11.17
  geist: ^1.3.1
  jiti: ^2.4.2
  lucide-react: ^0.479.0
  metro: ^0.80.12
  motion: ^12.5.0
  ms: ^2.1.3
  mysql2: ^3.9.2
  nanoid: ^5.0.7
  next-intl: ^4.0.0
  next-safe-action: ^8.0.7
  next-themes: ^0.4.0
  object.groupby: ^1.0.3
  ora: ^8.0.1
  posthog-js: ^1.149.0
  posthog-node: ^4.3.1
  react-day-picker: ^9.4.4
  react-email: 3.0.7
  react-hook-form: ^7.60.0
  react-icons: ^5.3.0
  react-native: ~0.74.5
  react-native-css-interop: ~0.0.34
  react-native-dialog: ^9.3.0
  react-native-gesture-handler: ~2.20.2
  react-native-keyboard-controller: ^1.13.4
  react-native-modal-datetime-picker: ^18.0.0
  react-native-reanimated: ~3.10.1
  react-native-safe-area-context: ~4.10.5
  react-native-screens: ~3.34.1
  react-native-svg: ^15.6.0
  react-resizable-panels: ^2.0.14
  react-spring: ^9.7.3
  resend: ^4.0.1
  rrule: ^2.8.1
  server-only: ^0.0.1
  sonner: ^2.0.0
  superjson: 2.2.1
  tailwind-merge: ^3.0.2
  tamagui: ^1.110.5
  tsx: 4.7.3
  tw-animate-css: ^1.3.8
  typescript: ^5.9.2
  ultracite: ^5.3.9
  use-intl: ^4.0.0
  vaul: ^1.0.0
  vitest: ^3.0.6
  yaml: 2.7.0
  zod: ^4.0.0
  zustand: ^5.0.0

catalogs:
  babel:
    '@babel/core': ^7.26.0
    '@babel/preset-env': ^7.26.0
    '@babel/runtime': ^7.26.0
  expo:
    '@expo/metro-config': ^0.18.11
    expo: ~51.0.39
    expo-av: ~14.0.7
    expo-blur: ^13.0.2
    expo-constants: ~16.0.2
    expo-dev-client: ~4.0.29
    expo-device: ~6.0.2
    expo-font: ~12.0.10
    expo-haptics: ~13.0.1
    expo-linking: ~6.3.1
    expo-localization: ~15.0.3
    expo-notifications: ~0.28.17
    expo-router: ~3.5.24
    expo-secure-store: ^13.0.2
    expo-server-sdk: ^3.11.0
    expo-splash-screen: ~0.27.7
    expo-status-bar: ~1.12.1
  formatjs:
    '@formatjs/intl-getcanonicallocales': ^2.3.0
    '@formatjs/intl-locale': ^4.0.0
    '@formatjs/intl-pluralrules': ^5.2.14
    '@formatjs/intl-relativetimeformat': ^11.2.14
  next:
    next: ^15.5.3
  react:
    '@types/react': ^19.1.0
    '@types/react-dom': ^19.1.0
    react: ^19.1.0
    react-dom: ^19.1.0
  react-big-calendar:
    '@types/react-big-calendar': ^1.16.1
    react-big-calendar: ^1.18.0
  tailwindcss:
    '@tailwindcss/postcss': ^4.0.12
    tailwindcss: ^4.0.12
  tanstack-query:
    '@tanstack/react-query': ^5.66.5
    '@tanstack/react-query-devtools': ^5.32.0
  trpc:
    '@trpc/client': ^11.0.0
    '@trpc/react-query': ^11.0.0
    '@trpc/server': ^11.0.0
    '@trpc/tanstack-react-query': ^11.0.0
  turbo:
    '@turbo/gen': ^2.5.6
    turbo: ^2.5.6
