packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.15.0
  prettier: ^3.3.2
  typescript: ^5.5.4
  zod: ^3.23.8
  tailwindcss: ^3.4.15
  "@tanstack/react-query": ^5.61.0
  "@trpc/client": ^11.0.0-rc.638
  "@trpc/react-query": ^11.0.0-rc.638
  "@trpc/server": ^11.0.0-rc.638
  "@types/node": ^20.17.6

catalogs:
  react19:
    react: rc
    react-dom: rc
    "@types/react": npm:types-react@rc
    "@types/react-dom": npm:types-react-dom@rc
