packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  turbo:
    turbo: ^2.4.2
    "@turbo/gen": ^2.4.2
    eslint-plugin-turbo: ^2.4.2

  next:
    next: ^15.2.2
    "@next/eslint-plugin-next": ^15.2.2

  trpc:
    "@trpc/client": ^11.0.0-rc.772
    "@trpc/tanstack-react-query": ^11.0.0-rc.772
    "@trpc/react-query": ^11.0.0-rc.772
    "@trpc/server": ^11.0.0-rc.772

  react:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    eslint-plugin-react-hooks: ^5.0.0

  babel:
    "@babel/core": ^7.26.0
    "@babel/preset-env": ^7.26.0
    "@babel/runtime": ^7.26.0

  react-big-calendar:
    react-big-calendar: ^1.15.0
    "@types/react-big-calendar": ^1.15.0

  expo:
    "@expo/metro-config": ^0.18.11
    expo-blur: ^13.0.2
    expo-notifications: ~0.28.17
    expo-splash-screen: ~0.27.7
    expo: ~51.0.39
    expo-av: ~14.0.7
    expo-constants: ~16.0.2
    expo-dev-client: ~4.0.29
    expo-device: ~6.0.2
    expo-font: ~12.0.10
    expo-haptics: ~13.0.1
    expo-linking: ~6.3.1
    expo-localization: ~15.0.3
    expo-router: ~3.5.24
    expo-secure-store: ^13.0.2
    expo-server-sdk: ^3.11.0
    expo-status-bar: ~1.12.1

  formatjs:
    "@formatjs/intl-getcanonicallocales": ^2.3.0
    "@formatjs/intl-locale": ^4.0.0
    "@formatjs/intl-pluralrules": ^5.2.14
    "@formatjs/intl-relativetimeformat": ^11.2.14

  tanstack-query:
    "@tanstack/react-query": ^5.66.5
    "@tanstack/react-query-devtools": ^5.32.0

catalog:
  "@bacons/text-decoder": ^0.0.0
  "@casl/ability": ^6.7.3
  "@clack/prompts": ^0.7.0
  "@eslint/compat": ^1.2.3
  "@formkit/auto-animate": ^0.8.2
  "@hookform/resolvers": ^3.9.0
  "@ianvs/prettier-plugin-sort-imports": ^4.4.0
  "@motify/components": ^0.18.0
  "@node-rs/argon2": ^1.8.3
  "@oslojs/crypto": ^1.0.1
  "@oslojs/encoding": ^1.1.0
  "@radix-ui/react-alert-dialog": ^1.1.4
  "@radix-ui/react-avatar": ^1.1.2
  "@radix-ui/react-checkbox": ^1.1.3
  "@radix-ui/react-context-menu": ^2.2.4
  "@radix-ui/react-dialog": ^1.1.4
  "@radix-ui/react-dropdown-menu": ^2.1.4
  "@radix-ui/react-label": ^2.1.1
  "@radix-ui/react-navigation-menu": ^1.2.3
  "@radix-ui/react-popover": ^1.1.4
  "@radix-ui/react-radio-group": ^1.2.2
  "@radix-ui/react-scroll-area": ^1.2.2
  "@radix-ui/react-select": ^2.1.4
  "@radix-ui/react-separator": ^1.1.1
  "@radix-ui/react-slot": ^1.1.1
  "@radix-ui/react-switch": ^1.1.2
  "@radix-ui/react-tabs": ^1.1.2
  "@radix-ui/react-toast": ^1.2.4
  "@radix-ui/react-toggle": ^1.1.1
  "@radix-ui/react-tooltip": ^1.1.6
  "@radix-ui/react-visually-hidden": ^1.1.1
  "@react-email/components": ^0.0.33
  "@react-email/render": 0.0.13
  "@react-native-async-storage/async-storage": 1.23.1
  "@react-native-community/datetimepicker": ^8.2.0
  "@react-native-google-signin/google-signin": ^12.2.1
  "@shopify/flash-list": 1.6.4
  "@t3-oss/env-core": ^0.9.2
  "@t3-oss/env-nextjs": ^0.11.1
  "@tamagui/babel-plugin": ^1.110.5
  "@tamagui/cli": ^1.110.5
  "@tamagui/config": ^1.110.5
  "@tamagui/font-inter": ^1.110.5
  "@tamagui/lucide-icons": ^1.110.5
  "@tamagui/toast": ^1.110.5
  "@tanstack/react-table": ^8.16.0
  "@types/babel__core": ^7.20.5
  "@types/deep-diff": ^1.0.5
  "@types/ms": ^0.7.34
  "@types/node": ^20.17.6
  "@types/object.groupby": ^1.0.4
  "@typescript-eslint/eslint-plugin": ^8.15.0
  "@upstash/qstash": ^2.7.12
  "@upstash/redis": ^1.31.6
  "@vercel/analytics": ^1.2.2
  "@vercel/speed-insights": ^1.0.10
  arctic: ^1.9.1
  burnt: ^0.12.2
  chalk: ^5.3.0
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  cmdk: ^0.2.1
  cobe: ^0.6.3
  date-fns: ^3.6.0
  dayjs: ^1.11.11
  deep-diff: ^1.0.2
  discord-api-types: ^0.37.91
  dotenv-cli: ^7.4.4
  drizzle-kit: ^0.28.1
  drizzle-orm: ^0.36.3
  drizzle-seed: ^0.3.1
  drizzle-zod: ^0.5.1
  embla-carousel-react: 8.0.0-rc22
  eslint: ^9.15.0
  eslint-plugin-drizzle: ^0.2.3
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.2
  framer-motion: ^11.11.17
  motion: ^12.5.0
  geist: ^1.3.1
  jiti: ^2.3.3
  lucide-react: ^0.453.0
  metro: ^0.80.12
  ms: ^2.1.3
  mysql2: ^3.9.2
  nanoid: ^5.0.7
  next-intl: ^3.25.1
  next-safe-action: 7.1.4-experimental.1
  next-themes: ^0.3.0
  object.groupby: ^1.0.3
  ora: ^8.0.1
  postcss: ^8.4.49
  posthog-js: ^1.149.0
  posthog-node: ^4.3.1
  prettier: ^3.3.2
  prettier-plugin-tailwindcss: ^0.6.9
  react-day-picker: ^9.4.4
  react-email: 3.0.7
  react-hook-form: ^7.53.2
  react-icons: ^5.3.0
  react-native: ~0.74.5
  react-native-css-interop: ~0.0.34
  react-native-dialog: ^9.3.0
  react-native-gesture-handler: ~2.20.2
  react-native-keyboard-controller: ^1.13.4
  react-native-modal-datetime-picker: ^18.0.0
  react-native-reanimated: ~3.10.1
  react-native-safe-area-context: ~4.10.5
  react-native-screens: ~3.34.1
  react-native-svg: ^15.6.0
  react-resizable-panels: ^2.0.14
  react-spring: ^9.7.3
  resend: ^4.0.1
  rrule: ^2.8.1
  server-only: ^0.0.1
  sonner: ^1.7.0
  superjson: 2.2.1
  tailwind-merge: ^2.5.3
  tailwindcss: ^3.4.15
  tailwindcss-animate: ^1.0.7
  tamagui: ^1.110.5
  tsup: ^8.0.2
  tsx: 4.7.3
  typescript: ^5.5.4
  typescript-eslint: ^8.15.0
  use-intl: ^3.20.0
  vaul: ^1.0.0
  vitest: ^3.0.6
  zod: ^3.23.8
  zustand: ^5.0.0
