packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.15.0
  prettier: ^3.3.2
  typescript: ^5.5.4
  vitest: ^3.0.6
  zod: ^3.23.8
  tailwindcss: ^3.4.15
  "@tanstack/react-query": ^5.66.5
  "@trpc/client": ^11.0.0-rc.772
  "@trpc/tanstack-react-query": ^11.0.0-rc.772
  "@trpc/react-query": ^11.0.0-rc.772
  "@trpc/server": ^11.0.0-rc.772
  "@types/node": ^20.17.6

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
