name: CI

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened, edited, closed] # <--- **IMPORTANT** to subscribe to these events // https://drift.trpc.io/docs/github
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup
        with:
          skip-turbo: true
          skip-node: true

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: tsc
        run: turbo tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Test
        run: turbo test
# upload-drift:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v4

#     - name: Setup
#       uses: ./tooling/github/setup

#     - name: Upload Drift
#       run: cd packages/api && pnpm trpc upload -vv # optional: -vv for verbose output
#       env:
#         API_KEY: ${{ secrets.DRIFT_API_KEY }}
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
