name: CI

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened, edited, closed]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  generate-prisma-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm turbo db:generate

      - name: Generate cache key and set as output
        run: echo "CACHE_KEY=$(date +%s)" >> $GITHUB_ENV

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ env.CACHE_KEY }}

  lint:
    needs: generate-prisma-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ env.CACHE_KEY }}
      - name: Copy env
        run: cp .env.example .env
        
      - name: Lint
        run: pnpm lint && pnpm lint:ws

  format:
    needs: generate-prisma-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ env.CACHE_KEY }}
      - name: Format
        run: pnpm format

  typecheck:
    needs: generate-prisma-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ env.CACHE_KEY }}
      - name: Typecheck
        run: turbo typecheck

  upload-drift:
    needs: generate-prisma-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ env.CACHE_KEY }}
      - name: Upload Drift
        run: cd packages/api && pnpm trpc upload -vv
        env:
          API_KEY: ${{ secrets.DRIFT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
